server:
  port: 8082
spring:
  profiles:
    active: chy
  datasource:
    url: jdbc:mysql://localhost:3306/center_user
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 192.168.50.107:8848
        # 指定集群名称
        cluster-name: BJ
        # 指定namespace
        namespace: d791c206-35b6-4256-907a-81f4672f2454
    stream:
      rocketmq:
        binder:
          name-server: inner-mq.gbank.club:9876
      bindings:
        input:
          destination: add-bonus
          group: binder-group
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: center-user
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug
jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true