server:
  port: 8040
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.107:8848
        namespace: d791c206-35b6-4256-907a-81f4672f2454
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - PreLog=a,b
      routes:
        - id: user_route
          uri: lb://center-user
          predicates:
            - Path=/users/**
        - id: content_route
          uri: lb://center-content
          predicates:
            - Path=/shares/**,/admin/**

# http://localhost:8040/actuator/gateway/routes 展示所有路由列表
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#logging:
#  level:
#    org.springframework.cloud.gateway: trace